apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vdi-platform
  name: vdi-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: vdi-platform
  name: vdi-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: vdi-platform
roleRef:
  kind: Role
  name: vdi-role
  apiVersion: rbac.authorization.k8s.io/v1
