apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vdi-manager
  labels:
    app: vdi-manager
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5000
    protocol: TCP
  selector:
    app: vdi-manager
