apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vdi-desktop
  labels:
    app: vdi-desktop
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5901
    protocol: TCP
  selector:
    app: vdi-desktop
