replicaCount: 2
image:
  repository: myrepo/vdi-desktop
  tag: "1.0"
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 5901
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"
hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70
