replicaCount: 2
image:
  repository: myrepo/vdi-manager
  tag: "1.0"
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 5000
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
hpa:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilization: 70
